### ISSUE TITLE
Contacts BMLT

### ISSUE THREAD

**Issue by timbdesigns** [bmlt-enabled/contacts-bmlt#17]
The cities are only displaying on the first area and not on remaining areas on the area services page for the Wisconsin Region of Narcotics Anonymous. http://wisconsinna.org/members/area-services/

**Comment by pjaudiomv** [comment]
Hey. Looks like your server is on 3.0.2 and the latest version is only fully compatible with 3.0.4 and above see https://github.com/bmlt-enabled/contacts-bmlt/blob/main/readme.txt#L83

**Comment by pjaudiomv** [comment]
Closing as looks like it's updated and working

**Comment by timbdesigns** [comment]
Thank you!
